/**
 * The `window.sumaFiles` contract — TYPES ONLY.
 *
 * This app renders at `suma://files` inside a hardened WebContents with no
 * Node integration (PRD §8.1), so every privileged operation crosses a preload
 * bridge that the desktop stream owns and injects. Nothing here executes; this
 * file is the shape the UI codes against, and `mock-bridge.ts` is the
 * standalone stand-in so `vite build` / `vite dev` work without Electron.
 *
 * Channel mapping (implemented in the desktop stream; `channel-bridge.ts` is
 * the adapter that performs it when the preload injects the raw channels):
 *
 * | bridge method        | IPC channel            |
 * | -------------------- | ---------------------- |
 * | `context`            | `files:context`        |
 * | `list`               | `files:list`           |
 * | `stat`               | `files:stat`           |
 * | `read`               | `files:read`           |
 * | `upload`             | `files:upload`         |
 * | `download`           | `files:download`       |
 * | `remove`             | `files:delete`         |
 * | `quota`              | `files:quota`          |
 * | `listTransfers`      | `transfers:list`       |
 * | `cancelTransfer`     | `transfers:cancel`     |
 * | `onFilesChanged`     | `files:changed`        |
 * | `onTransfersUpdated` | `transfers:updated`    |
 * | `onUploadProgress`   | `files:uploadProgress` |
 *
 * Three of those channels exist because the UI needs them and the §8.6 channel
 * list does not enumerate them, so they were added deliberately:
 *
 * - `files:read` — inline preview needs a bounded byte range. Bounded on
 *   purpose, on both sides: the UI never asks for a whole file to draw a
 *   preview, and main clamps whatever it is asked for.
 * - `files:context` — the transfers list must name the device a cloud fetch
 *   came from, which means resolving `Transfer.originDeviceId` to a label.
 *   It carries device ids and display names and nothing else.
 * - `files:uploadProgress` — `upload()` resolves only at the end, and only
 *   main knows how much of a file the store already had (chunk dedup).
 *
 * What is deliberately absent: anything that would let this page reach the
 * network itself, and anything that would carry a credential toward the
 * compute plane. Cloud fetches are created by the main process from a
 * `will-download` intercept that already ran `cloudFetchEligibility`; this app
 * only ever *observes* them (§8.6 — the sealed one-shot request is deleted, and
 * authenticated downloads stay on this Mac).
 */

import type { FileEntry, QuotaState, Transfer } from "@suma/protocol";
// Type-only, for the `window.sumaFiles` declaration at the bottom: the
// injected object may be this bridge or the channel API the adapter wraps.
import type { InjectedFilesBridge } from "./channel-bridge";

/** Detach an event subscription. */
export type Unsubscribe = () => void;

/** A device that may appear as `Transfer.originDeviceId`. */
export interface FilesDevice {
  id: string;
  name: string;
}

export interface FilesContext {
  /** This Mac, so the transfers list can say "this Mac" instead of a name. */
  thisDeviceId: string | null;
  devices: FilesDevice[];
  /**
   * The one cloud-native root (`~/cloud`, canonical in R2). Everything the
   * Files app browses lives under it — the rest of `$HOME` is a volume with
   * snapshots and is NOT presented here as having a canonical cloud location.
   */
  cloudRoot: string;
  /** V1 truth: `$HOME` and its snapshots are not end-to-end encrypted (§8.6). */
  endToEndEncrypted: boolean;
}

/**
 * A bounded slice of a file, for inline preview only.
 *
 * The buffer is spelled `Uint8Array<ArrayBuffer>` rather than plain
 * `Uint8Array` because it must be usable as a `BlobPart` for image previews:
 * structured clone never hands back a SharedArrayBuffer-backed view, and the
 * type should say so instead of forcing a cast at the use site.
 */
export interface FileBytes {
  data: Uint8Array<ArrayBuffer>;
  /** True when the file is longer than the slice returned. */
  truncated: boolean;
  totalBytes: number;
}

export interface UploadInput {
  /**
   * Generated by this app so progress events can be correlated before
   * `upload()` resolves.
   */
  uploadId: string;
  /** Destination path; the main process re-normalizes it with `normalizeVfsPath`. */
  path: string;
  contentType: string | null;
  data: Uint8Array<ArrayBuffer>;
}

export type UploadState = "hashing" | "uploading" | "completed" | "failed";

export interface UploadProgress {
  uploadId: string;
  path: string;
  /**
   * Bytes accepted so far. Chunk-level dedup can make this jump: identical
   * chunks are never re-sent, so the UI treats this as progress, not traffic.
   */
  sentBytes: number;
  totalBytes: number;
  state: UploadState;
  error: string | null;
}

export type UploadResult =
  | { ok: true; entry: FileEntry }
  | { ok: false; reason: "quota" | "rejected" | "error"; message: string };

export type DownloadResult =
  | { ok: true; savePath: string }
  | { ok: false; reason: "missing" | "cancelled" | "error"; message: string };

export type DeleteResult = { ok: true } | { ok: false; message: string };

export interface SumaFilesBridge {
  context(): Promise<FilesContext>;
  /** Entries whose path starts with `prefix` ("/" for everything). */
  list(prefix: string): Promise<FileEntry[]>;
  stat(path: string): Promise<FileEntry | null>;
  /** First `maxBytes` of a file; null when it no longer exists. */
  read(path: string, maxBytes: number): Promise<FileBytes | null>;
  upload(input: UploadInput): Promise<UploadResult>;
  /** Hydrate to local disk (chunk cache); resolves with where it landed. */
  download(path: string): Promise<DownloadResult>;
  remove(path: string): Promise<DeleteResult>;
  quota(): Promise<QuotaState>;
  listTransfers(): Promise<Transfer[]>;
  cancelTransfer(transferId: string): Promise<void>;
  onFilesChanged(handler: () => void): Unsubscribe;
  onTransfersUpdated(handler: (transfers: Transfer[]) => void): Unsubscribe;
  onUploadProgress(handler: (progress: UploadProgress) => void): Unsubscribe;
}

declare global {
  interface Window {
    /**
     * Injected by the desktop preload; absent when running standalone.
     *
     * Either shape can arrive: this interface, or the allowlisted channel API
     * (`{ invoke, on }`). `adaptBridge` in `channel-bridge.ts` turns the second
     * into the first, and `resolveBridge` is the only place that looks.
     */
    sumaFiles?: InjectedFilesBridge;
  }
}
